version: '3.1'
services:
  cfssl:
    image: blackducksoftware/hub-cfssl:2018.9.0
    volumes: ['cert-volume:/etc/cfssl']
    healthcheck:
      test: [CMD, /usr/local/bin/docker-healthcheck.sh, 'http://localhost:8888/api/v1/cfssl/scaninfo']
      interval: 30s
      timeout: 10s
      retries: 5
    user: cfssl:root
    deploy:
      mode: replicated
      restart_policy: {condition: on-failure, delay: 5s, window: 60s}
      resources:
        limits: {memory: 640M}
        reservations: {memory: 640M}
  logstash:
    image: blackducksoftware/hub-logstash:2018.9.0
    volumes: ['log-volume:/var/lib/logstash/data']
    healthcheck:
      test: [CMD, /usr/local/bin/docker-healthcheck.sh, 'http://localhost:9600/']
      interval: 30s
      timeout: 10s
      retries: 5
    user: logstash:root
    deploy:
      mode: replicated
      restart_policy: {condition: on-failure, delay: 5s, window: 60s}
      resources:
        limits: {memory: 1024M}
        reservations: {memory: 1024M}
  registration:
    image: blackducksoftware/hub-registration:2018.9.0
    links: [logstash]
    volumes: ['config-volume:/opt/blackduck/hub/hub-registration/config']
    env_file: hub-proxy.env
    healthcheck:
      test: [CMD, /usr/local/bin/docker-healthcheck.sh, 'https://localhost:8443/registration/health-checks/liveness',
        /opt/blackduck/hub/hub-registration/security/root.crt]
      interval: 30s
      timeout: 10s
      retries: 5
    user: tomcat:root
    deploy:
      mode: replicated
      restart_policy: {condition: on-failure, delay: 5s, window: 60s}
      resources:
        limits: {memory: 640M}
        reservations: {memory: 640M}
  zookeeper:
    image: blackducksoftware/hub-zookeeper:2018.9.0
    links: [logstash]
    volumes: ['zookeeper-data-volume:/opt/blackduck/zookeeper/data', 'zookeeper-datalog-volume:/opt/blackduck/zookeeper/datalog']
    healthcheck:
      test: [CMD, zkServer.sh, status, /opt/blackduck/zookeeper/conf/zoo.cfg]
      interval: 30s
      timeout: 10s
      retries: 5
    user: zookeeper:root
    deploy:
      mode: replicated
      restart_policy: {condition: on-failure, delay: 5s, window: 60s}
      resources:
        limits: {memory: 384M}
        reservations: {memory: 384M}
  solr:
    image: blackducksoftware/hub-solr:2018.9.0
    links: [logstash, zookeeper]
    volumes: ['solr6-volume:/opt/blackduck/hub/solr/cores.data']
    healthcheck:
      test: [CMD, /usr/local/bin/docker-healthcheck.sh, 'http://localhost:8983/solr/project/admin/ping?wt=json']
      interval: 30s
      timeout: 10s
      retries: 5
    user: solr:root
    deploy:
      mode: replicated
      restart_policy: {condition: on-failure, delay: 5s, window: 60s}
      resources:
        limits: {memory: 640M}
        reservations: {memory: 640M}
  authentication:
    image: blackducksoftware/hub-authentication:2018.9.0
    links: [cfssl, logstash, registration, zookeeper]
    volumes: ['authentication-volume:/opt/blackduck/hub/hub-authentication/security']
    env_file: [hub-proxy.env, hub-postgres.env]
    healthcheck:
      test: [CMD, /usr/local/bin/docker-healthcheck.sh, 'https://127.0.0.1:8443/api/health-checks/liveness',
        /opt/blackduck/hub/hub-authentication/security/root.crt]
      interval: 30s
      timeout: 60s
      retries: 15
    user: authentication:root
    environment: {HUB_MAX_MEMORY: 512m}
    deploy:
      mode: replicated
      restart_policy: {condition: on-failure, delay: 5s, window: 60s}
      resources:
        limits: {cpus: '1', memory: 1024M}
        reservations: {memory: 1024M}
  webapp:
    image: blackducksoftware/hub-webapp:2018.9.0
    links: [cfssl, logstash, registration, zookeeper, solr]
    volumes: ['log-volume:/opt/blackduck/hub/logs', 'webapp-volume:/opt/blackduck/hub/hub-webapp/security']
    env_file: [hub-proxy.env, hub-postgres.env]
    healthcheck:
      test: [CMD, /usr/local/bin/docker-healthcheck.sh, 'https://127.0.0.1:8443/api/health-checks/liveness',
        /opt/blackduck/hub/hub-webapp/security/root.crt]
      interval: 30s
      timeout: 60s
      retries: 15
    user: tomcat:root
    environment: {HUB_MAX_MEMORY: 2048m}
    deploy:
      mode: replicated
      restart_policy: {condition: on-failure, delay: 5s, window: 60s}
      resources:
        limits: {cpus: '1', memory: 2560M}
        reservations: {cpus: '1', memory: 2560M}
  scan:
    image: blackducksoftware/hub-scan:2018.9.0
    links: [cfssl, logstash, registration, zookeeper]
    volumes: ['scan-volume:/opt/blackduck/hub/hub-scan/security']
    env_file: [hub-proxy.env, hub-postgres.env]
    healthcheck:
      test: [CMD, /usr/local/bin/docker-healthcheck.sh, 'https://127.0.0.1:8443/api/health-checks/liveness',
        /opt/blackduck/hub/hub-scan/security/root.crt]
      interval: 30s
      timeout: 60s
      retries: 15
    user: tomcat:root
    environment: {HUB_MAX_MEMORY: 2048m}
    deploy:
      mode: replicated
      restart_policy: {condition: on-failure, delay: 5s, window: 60s}
      resources:
        limits: {cpus: '1', memory: 2560M}
        reservations: {cpus: '1', memory: 2560M}
  jobrunner:
    image: blackducksoftware/hub-jobrunner:2018.9.0
    links: [cfssl, logstash, registration, zookeeper, solr]
    env_file: [hub-proxy.env, hub-postgres.env]
    healthcheck:
      test: [CMD, /usr/local/bin/docker-healthcheck.sh]
      interval: 30s
      timeout: 60s
      retries: 15
    user: jobrunner:root
    environment: {HUB_MAX_MEMORY: 4096m}
    deploy:
      mode: replicated
      restart_policy: {condition: on-failure, delay: 5s, window: 60s}
      resources:
        limits: {cpus: '1', memory: 4608M}
        reservations: {cpus: '1', memory: 4608M}
  webserver:
    image: blackducksoftware/hub-nginx:2018.9.0
    ports: ['443:8443']
    env_file: hub-webserver.env
    links: [webapp, cfssl, documentation]
    volumes: ['webserver-volume:/opt/blackduck/hub/webserver/security']
    healthcheck:
      test: [CMD, /usr/local/bin/docker-healthcheck.sh, 'https://localhost:8443/health-checks/liveness',
        /opt/blackduck/hub/webserver/security/root.crt]
      interval: 30s
      timeout: 10s
      retries: 5
    user: nginx:root
    deploy:
      mode: replicated
      restart_policy: {condition: on-failure, delay: 15s, window: 60s}
      resources:
        limits: {memory: 512M}
        reservations: {memory: 512M}
  documentation:
    image: blackducksoftware/hub-documentation:2018.9.0
    links: [logstash]
    user: tomcat:root
    healthcheck:
      test: [CMD, /usr/local/bin/docker-healthcheck.sh, 'https://127.0.0.1:8443/hubdoc/health-checks/liveness',
        /opt/blackduck/hub/hub-documentation/security/root.crt]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      mode: replicated
      restart_policy: {condition: on-failure, delay: 5s, window: 60s}
      resources:
        limits: {memory: 512M}
        reservations: {memory: 512M}
volumes: {authentication-volume: null, cert-volume: null, config-volume: null, log-volume: null,
  webserver-volume: null, webapp-volume: null, scan-volume: null, solr6-volume: null,
  monitor-log-volume: null, zookeeper-data-volume: null, zookeeper-datalog-volume: null}
